# Generated by Django 3.2 on 2022-09-02 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_remove_question_question_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
