# Generated by Django 3.2 on 2022-08-30 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20220830_0248'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
