# Generated by Django 3.2 on 2022-08-30 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0002_delete_answer'),
        ('choices', '0002_delete_choice'),
        ('questions', '0004_alter_question_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
